#define HAVE_DLFCN_H 1
#define HAVE_ENVIRONMENT_CHECKING 1
#define HAVE_INTTYPES_H 1
#define HAVE_ISO_FORTRAN_ENV 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define LT_OBJDIR ".libs/"
#define PACKAGE "elpa"
#define PACKAGE_BUGREPORT "elpa-library@rzg.mpg.de"
#define PACKAGE_NAME "elpa"
#define PACKAGE_STRING "elpa 2014.06.002"
#define PACKAGE_TARNAME "elpa"
#define PACKAGE_URL ""
#define PACKAGE_VERSION "2014.06.002"
#define STDC_HEADERS 1
#define VERSION "2014.06.002"
#define WITH_COMPLEX_GENERIC_KERNEL 1
#define WITH_OPENMP 1
#define WITH_REAL_GENERIC_KERNEL 1

