gcc-env:
  compiler:
      - toolchain: gcc
        spec: gcc
  mpi:
      spec: cray-mpich@8.1.30
      gpu: cuda
  unify: when_possible
  specs:
  - sirius@develop +python +vdwxc +apps +tests +dlaf
  - sirius@develop +elpa
  variants:
  - +mpi
  - +cuda
  - cuda_arch=90
  views:
    sirius:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
