gcc-env:
  compiler: [gcc]
  network:
    mpi: cray-mpich@8.1.32
    specs: ['libfabric@1.22.0']
  unify: true
  specs:
  - sirius@develop +elpa +python +vdwxc +apps +tests +scalapack +nlcglib +dftd3 +dftd4
  - nlcglib@1.3.0
  - libvdwxc@master # 0.5 is broken
  - kokkos+serial
  variants:
  - +mpi
  views:
    sirius:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
