gcc-env:
  compiler: [gcc]
  network:
    mpi: cray-mpich@8.1.32
  unify: when_possible
  specs:
  - sirius@develop +python +vdwxc +apps +tests +scalapack +nlcglib +dftd3 +dftd4
  - sirius@develop +elpa
  - nlcglib@1.2
  variants:
  - +mpi
  views:
    sirius:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
