gcc-env:
  compiler: [gcc]
  network:
      mpi: cray-mpich@9.1.0+cuda
      specs: ['libfabric@2.4.0+cuda']
  unify: true
  specs:
  - sirius@develop +python +vdwxc +elpa +apps +tests +scalapack +nlcglib +dftd3 ~dftd4 +memory_pool
  # - umpire+fortran # +fortran works around a bug in spack/umpire recipe
  - cuda@13
  - umpire~mpi # umpire+mpi~fortran fails during package.py processing
  - nlcglib@1.3.0 +cuda
  - libvdwxc@0.5
  - kokkos+serial@4.7.02
  variants:
  - +cuda
  - cuda_arch=90
  views:
    sirius:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
