name: sirius-uenv-base
version: 2
spack:
  commit: releases/v1.0
  repo: https://github.com/spack/spack.git
  packages:
    repo: https://github.com/spack/spack-packages.git
    commit: 1f1e66d43b5b97fe8bd85c17f8eee62530febb3a
store: /user-environment
description: SIRIUS dependencies for SIRIUS CI
