sirius-env:
  compiler: [gcc]
  network:
      mpi: cray-mpich@8.1.32+rocm
      specs: [ 'libfabric@2.3 +rocm' ]
  unify: when_possible
  specs:
  - sirius@develop ~python +vdwxc +apps +tests +dlaf +scalapack +rocm +dftd4 +dftd3
  - kokkos@4.7.02+serial
  - sirius@develop +elpa
  - nlcglib@1.3.0
  - eigen@3
  - hip@6.3.3 ^mesa@23.3.6
  variants:
  - amdgpu_target=gfx942
  - amdgpu_target_sram_ecc=gfx942
  views:
    sirius:
      link: roots
      uenv:
        add_compilers: true
        prefix_paths:
          LD_LIBRARY_PATH: [lib, lib64]
