#!/usr/bin/env python3

import json
import argparse
import matplotlib.pyplot as plt

def main():
    parser = argparse.ArgumentParser(description="Plot radial functions generated by B-splines")
    parser.add_argument("input", help="Input JSON file")
    parser.add_argument("--u", action="store_true", help="plot u(r) instead of p(r)=r*u(r)")
    parser.add_argument("--idxrf", type=int, required=True, help="Radial-function index to plot")
    parser.add_argument("-o", "--output", default="radial_function_u.pdf", help="Output PDF file")
    args = parser.parse_args()

    with open(args.input) as f:
        data = json.load(f)

    r = data["r"]
    key = "u" if args.u else "p"
    y = data[key]
    evals = data["eval"]

    fig, ax = plt.subplots(figsize=(8, 5))

    ax.plot(r, y[args.idxrf], label=f"{args.idxrf}: E={evals[args.idxrf]:.8f}")

    ax.set_xlabel("r")
    ax.set_ylabel("u(r)" if args.u else "p(r) = r u(r)")
    ax.set_title(f"B-spline radial functions, l={data.get('l')}, order={data.get('order')}")
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()

    fig.savefig(args.output, bbox_inches="tight")


if __name__ == "__main__":
    main()
