include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage
  - build
  - test

build base uenv gh200:
  extends: .uenv-builder-daint-gh200
  stage: baseimage
  timeout: 2h
  variables:
    UENV_NAME: sirius-gh200
    WATCH_FILECHANGES: ci/sirius-uenv-recipe/
    UENV_RECIPE: ci/sirius-uenv-recipe/
    UENV_VERSION: 1
    UENV_TAG: 0

build sirius cuda:
  extends: .uenv-runner-daint-gh200
  stage: build
  needs: ["build base uenv gh200"]
  image: sirius-gh200/1:0
  artifacts:
    paths:
      - builddir
  variables:
    SPEC: sirius +cuda +apps +tests
    CUDA_ARCH: 90
  script:
    - |
      #
      git clone --filter=tree:0 $(jq -r .spack.repo /user-environment/meta/configure.json) spack-clone
      git -C spack-clone checkout $(jq -r .spack.commit /user-environment/meta/configure.json)
      source ./spack-clone/share/spack/setup-env.sh
      ./ci/build-cuda.sh
