include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage
  - build
  - test

.f7t-secrets:
  variables:
    F7T_CLIENT_ID: $F7T_TDS_CLIENT_ID
    F7T_CLIENT_SECRET: $F7T_TDS_CLIENT_SECRET

build base uenv mi300:
  extends: [.uenv-builder-beverin-mi300, .f7t-secrets]
  stage: baseimage
  timeout: 24h
  variables:
    UENV_NAME: sirius-mi300
    UENV_RECIPE: ci/sirius-uenv-recipe-mi300/
    UENV_VERSION: v1
    SLURM_TIMELIMIT: 600

build sirius mi300:
  extends: [.uenv-runner-beverin-mi300, .f7t-secrets]
  stage: build
  needs: ["build base uenv mi300"]
  image: sirius-mi300/v1:$CI_PIPELINE_ID
  artifacts:
    paths:
      - builddir.tar
  variables:
    SPEC: sirius@develop +rocm +apps +tests +scalapack ~python +dftd4 +dftd3 +vdwxc build_type=RelWithDebInfo
    ROCM_ARCH: gfx942
    REPO: ./ci/spack_repo/sirius_ci
  script:
    - |
      #
      git clone --filter=tree:0 $(jq -r .spack.repo /user-environment/meta/configure.json) /dev/shm/spack-clone
      git -C /dev/shm/spack-clone checkout $(jq -r .spack.commit /user-environment/meta/configure.json)
      source /dev/shm/spack-clone/share/spack/setup-env.sh
      bwrap --dev-bind / / --tmpfs ~ -- ./ci/build-rocm.sh

.run_tests:
  extends: [.f7t-secrets]
  script:
    - |
      if [ $SLURM_LOCALID -eq 0 ]; then
        tar xf ./builddir.tar -C /
        touch /dev/shm/unpack_done_$CI_JOB_ID
      fi
    - |
      # wait for tar unpack
      while [ ! -f /dev/shm/unpack_done_$CI_JOB_ID ]; do
        sleep 0.2
      done

      stagedir=$(find /dev/shm/spack-stage -type d -name spack-stage-sirius-*)
      echo "stagedir: $stagedir"
      cd $stagedir/spack-build-*
      if [ "$SLURM_PROCID" == "0" ]; then
      $TEST_COMMAND -V
      else
      $TEST_COMMAND --output-on-failure
      fi

.run_tests_beverin:
  extends: [.uenv-runner-beverin-mi300, .run_tests]
  image: sirius-mi300/v1:$CI_PIPELINE_ID
  stage: test
  needs: ["build sirius mi300"]
  variables:
    SLURM_HINT: nomultithread
    SLURM_CPUS_PER_TASK: 8
    SLURM_CONSTRAINT: 'amdgpu_tpx'
    OMP_NUM_THREADS: 8
    OMP_PLACES: cores
    HSA_ENABLE_SDMA: 0
    SLURM_GPU_BIND: 'closest'
    MPICH_SMP_SINGLE_COPY_MODE: 'NONE'

beverin test gpu serial:
  extends: [.run_tests_beverin]
  variables:
    SLURM_TIMELIMIT: '60:00'
    SLURM_GPUS_PER_TASK: 1
    SLURM_GPUS: 1
    SLURM_NTASKS: 1
    SLURM_CPU_BIND: 'verbose'
    USE_MPI: 'YES'
    TEST_COMMAND: ctest -L gpu_serial_rocm

beverin test gpu band parallel:
  extends: [.run_tests_beverin]
  variables:
    SLURM_TIMELIMIT: '60:00'
    SLURM_GPUS_PER_TASK: 1
    SLURM_NTASKS: 12
    SLURM_CPU_BIND: 'verbose'
    USE_MPI: 'YES'
    TEST_COMMAND: ctest -L gpu_band_parallel --timeout 3600

beverin test gpu k-point parallel:
  extends: [.run_tests_beverin]
  variables:
    SLURM_NTASKS: 12
    SLURM_GPUS_PER_TASK: 1
    SLURM_CPU_BIND: 'verbose'
    USE_MPI: 'YES'
    TEST_COMMAND: ctest -L gpu_k_point_parallel

# eiger test cpu serial:
#   extends: [.run_tests_eiger]
#   variables:
#     OMP_NUM_THREADS: 8
#     SLURM_TIMELIMIT: '60:00'
#     SLURM_NTASKS: 1
#     SRUN_CPUS_PER_TASK: 8
#     USE_MPI: 'YES'
#     TEST_COMMAND: ctest -L cpu_serial

# eiger test cpu band parallel:
#   extends: [.run_tests_eiger]
#   variables:
#     OMP_NUM_THREADS: 8
#     SLURM_TIMELIMIT: '60:00'
#     SLURM_NTASKS: 4
#     SRUN_CPUS_PER_TASK: 8
#     USE_MPI: 'YES'
#     TEST_COMMAND: ctest -L cpu_band_parallel
