include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - baseimage
  - build
  - test

build base cuda image:
  extends: .container-builder-dynamic-name
  stage: baseimage
  timeout: 2h
  variables:
    DOCKERFILE: ci/baseimage.cuda.Dockerfile
    WATCH_FILECHANGES: ci/baseimage.cuda.Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/sirius-ci
    DOCKER_BUILD_ARGS: '["CUDA_ARCH=60"]'

build base rocm image:
  extends: .container-builder-dynamic-name
  stage: baseimage
  # rocm takes long to build
  timeout: 4h
  variables:
    DOCKERFILE: ci/baseimage.rocm.Dockerfile
    WATCH_FILECHANGES: ci/baseimage.rocm.Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/base/sirius-ci
    DOCKER_BUILD_ARGS: '["ROCM_ARCH=gfx90a"]'

build cuda image mkl:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: discard
    ENVPATH: "/sirius-env-cuda-mkl-mpich"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

build cuda image:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  variables:
    CSCS_REBUILD_POLICY: always
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: $CSCS_REGISTRY_PATH/sirius/sirius-ci:$CI_COMMIT_SHA
    ENVPATH: "/sirius-env-cuda"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

build rocm image:
  extends: .container-builder
  needs: ["build base rocm image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: discard
    ENVPATH: "/sirius-env-rocm"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

build elpa cuda image:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: discard
    ENVPATH: "/sirius-env-elpa"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

build sequential eigen-solver cuda image:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: discard
    ENVPATH: "/sirius-env-cuda-sequential"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

build fp32 cuda image:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: discard
    ENVPATH: "/sirius-env-fp32"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

build vdwxc cuda image:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: discard
    # we can't use MKL here because vdwxc needs parallel FFT and MKL doesn't provide it
    ENVPATH: "/sirius-env-vdwxc-cuda"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

build nlcg image:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: discard
    ENVPATH: "/sirius-env-nlcg"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

build clang image:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: discard
    # reuse openblas, libxc and spfft from gcc build
    ENVPATH: "/sirius-env-clang"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

build openmpi image:
  extends: .container-builder
  needs: ["build base cuda image"]
  stage: build
  variables:
    DOCKERFILE: ci/build.Dockerfile
    PERSIST_IMAGE_NAME: discard
    ENVPATH: "/sirius-env-openmpi"
    DOCKER_BUILD_ARGS: '["BASE_IMAGE=${BASE_IMAGE}", "ENVPATH=$ENVPATH"]'

.run_tests:
  extends: .container-runner-daint-gpu
  needs: ["build cuda image"]
  stage: test
  script:
    - cd /sirius-src/spack-build
    - |
      if [ "$SLURM_PROCID" == "0" ]; then
        $TEST_COMMAND -V
      else
        $TEST_COMMAND --output-on-failure
      fi
  image: $CSCS_REGISTRY_PATH/sirius/sirius-ci:$CI_COMMIT_SHA
  variables:
    CRAY_CUDA_MPS: 1
    GIT_STRATEGY: none
    MPICH_MAX_THREAD_SAFETY: multiple
    CSCS_REGISTRY_LOGIN: 'YES'
    PULL_IMAGE: 'YES'
    SLURM_HINT: nomultithread
    SLURM_JOB_NUM_NODES: 1
    SLURM_UNBUFFEREDIO: ''
    SLURM_WAIT: 0

gpu serial:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: 12
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: "60:00"
    TEST_COMMAND: ctest -L gpu_serial

gpu band parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: 3
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 3
    SLURM_NTASKS: 4
    SLURM_TIMELIMIT: "60:00"
    TEST_COMMAND: ctest -L gpu_band_parallel --timeout 3600
    USE_MPI: 'YES'

gpu k-point parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: 3
    SLURM_CONSTRAINT: gpu
    SLURM_CPUS_PER_TASK: 3
    SLURM_NTASKS: 4
    SLURM_TIMELIMIT: "30:00"
    TEST_COMMAND: ctest -L gpu_k_point_parallel
    USE_MPI: 'YES'

cpu single:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: 12
    SLURM_CONSTRAINT: gpu
    SLURM_CPU_BIND: sockets
    SLURM_CPUS_PER_TASK: 12
    SLURM_NTASKS: 1
    SLURM_TIMELIMIT: "60:00"
    TEST_COMMAND: ctest -L cpu_serial

cpu band parallel:
  extends: .run_tests
  variables:
    OMP_NUM_THREADS: 3
    SLURM_CONSTRAINT: gpu
    SLURM_CPU_BIND: sockets
    SLURM_CPUS_PER_TASK: 3
    SLURM_NTASKS: 4
    SLURM_TIMELIMIT: "60:00"
    TEST_COMMAND: ctest -L cpu_band_parallel --timeout 3600
    USE_MPI: 'YES'
