all:
	cd atoms && $(MAKE)
	cd dft_loop && $(MAKE)
	cd tests && $(MAKE)
	cd unit_tests && $(MAKE)
clean:
	cd atoms && $(MAKE) clean
	cd dft_loop && $(MAKE) clean
	cd tests && $(MAKE) clean
	cd unit_tests && $(MAKE) clean
