! Warning! This file is automatically generated using cpp_f90.py script!

!> @file generated.f90
!! @brierf Autogenerated interface to Fortran.
!
!> @brief Initialize the SIRIUS library.
!> @param [in] call_mpi_init If .true. then MPI_Init must be called prior to initialization.
subroutine sirius_initialize(call_mpi_init)
implicit none
logical(C_BOOL), intent(in) :: call_mpi_init
interface
subroutine sirius_initialize_aux(call_mpi_init)&
&bind(C, name="sirius_initialize")
use, intrinsic :: ISO_C_BINDING
logical(C_BOOL), intent(in) :: call_mpi_init
end subroutine
end interface
call sirius_initialize_aux(call_mpi_init)
end subroutine sirius_initialize

!> @brief Shut down the SIRIUS library
!> @param [in] call_mpi_fin If .true. then MPI_Finalize must be called after the shutdown.
subroutine sirius_finalize(call_mpi_fin)
implicit none
logical(C_BOOL), intent(in) :: call_mpi_fin
interface
subroutine sirius_finalize_aux(call_mpi_fin)&
&bind(C, name="sirius_finalize")
use, intrinsic :: ISO_C_BINDING
logical(C_BOOL), intent(in) :: call_mpi_fin
end subroutine
end interface
call sirius_finalize_aux(call_mpi_fin)
end subroutine sirius_finalize

!> @brief Check if the simulation context is initialized.
!> @param [in] handler Simulation context handler.
function sirius_context_initialized(handler) result(res)
implicit none
type(C_PTR), intent(in) :: handler
logical(C_BOOL) :: res
interface
function sirius_context_initialized_aux(handler) result(res)&
&bind(C, name="sirius_context_initialized")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: handler
logical(C_BOOL) :: res
end function
end interface
res = sirius_context_initialized_aux(handler)
end function sirius_context_initialized

!> @brief Create context of the simulation.
!> @param [out] handler Simulation context handler.
!> @param [in] fcomm Entire communicator of the simulation.
subroutine sirius_create_context_v2(handler,fcomm)
implicit none
type(C_PTR), intent(out) :: handler
integer(C_INT), intent(in) :: fcomm
interface
subroutine sirius_create_context_v2_aux(handler,fcomm)&
&bind(C, name="sirius_create_context_v2")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(out) :: handler
integer(C_INT), intent(in) :: fcomm
end subroutine
end interface
call sirius_create_context_v2_aux(handler,fcomm)
end subroutine sirius_create_context_v2

!> @brief Import parameters of simulation from a JSON string
!> @param [in] handler Simulation context handler.
!> @param [in] json_str JSON string with parameters.
subroutine sirius_import_parameters_v2(handler,json_str)
implicit none
type(C_PTR), intent(in) :: handler
character(C_CHAR), dimension(*), intent(in) :: json_str
interface
subroutine sirius_import_parameters_v2_aux(handler,json_str)&
&bind(C, name="sirius_import_parameters_v2")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: handler
character(C_CHAR), dimension(*), intent(in) :: json_str
end subroutine
end interface
call sirius_import_parameters_v2_aux(handler,json_str)
end subroutine sirius_import_parameters_v2

!> @brief Set parameters of the simulation.
!> @param [in] handler Simulation context handler
!> @param [in] lmax_apw Maximum orbital quantum number for APW functions.
!> @param [in] lmax_rho Maximum orbital quantum number for density.
!> @param [in] lmax_pot Maximum orbital quantum number for potential.
!> @param [in] num_bands Number of bands.
!> @param [in] num_mag_dims Number of magnetic dimensions.
!> @param [in] pw_cutoff Cutoff for G-vectors.
!> @param [in] gk_cutoff Cutoff for G+k-vectors.
!> @param [in] auto_rmt Set the automatic search of muffin-tin radii.
subroutine sirius_set_parameters(handler,lmax_apw,lmax_rho,lmax_pot,num_bands,nu&
&m_mag_dims,pw_cutoff,gk_cutoff,auto_rmt)
implicit none
type(C_PTR), intent(in) :: handler
integer(C_INT), optional, target, intent(in) :: lmax_apw
integer(C_INT), optional, target, intent(in) :: lmax_rho
integer(C_INT), optional, target, intent(in) :: lmax_pot
integer(C_INT), optional, target, intent(in) :: num_bands
integer(C_INT), optional, target, intent(in) :: num_mag_dims
real(C_DOUBLE), optional, target, intent(in) :: pw_cutoff
real(C_DOUBLE), optional, target, intent(in) :: gk_cutoff
integer(C_INT), optional, target, intent(in) :: auto_rmt
type(C_PTR) :: lmax_apw_ptr = C_NULL_PTR
type(C_PTR) :: lmax_rho_ptr = C_NULL_PTR
type(C_PTR) :: lmax_pot_ptr = C_NULL_PTR
type(C_PTR) :: num_bands_ptr = C_NULL_PTR
type(C_PTR) :: num_mag_dims_ptr = C_NULL_PTR
type(C_PTR) :: pw_cutoff_ptr = C_NULL_PTR
type(C_PTR) :: gk_cutoff_ptr = C_NULL_PTR
type(C_PTR) :: auto_rmt_ptr = C_NULL_PTR
interface
subroutine sirius_set_parameters_aux(handler,lmax_apw,lmax_rho,lmax_pot,num_band&
&s,num_mag_dims,pw_cutoff,gk_cutoff,auto_rmt)&
&bind(C, name="sirius_set_parameters")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: handler
type(C_PTR), value, intent(in) :: lmax_apw
type(C_PTR), value, intent(in) :: lmax_rho
type(C_PTR), value, intent(in) :: lmax_pot
type(C_PTR), value, intent(in) :: num_bands
type(C_PTR), value, intent(in) :: num_mag_dims
type(C_PTR), value, intent(in) :: pw_cutoff
type(C_PTR), value, intent(in) :: gk_cutoff
type(C_PTR), value, intent(in) :: auto_rmt
end subroutine
end interface
if (present(lmax_apw)) lmax_apw_ptr = C_LOC(lmax_apw)
if (present(lmax_rho)) lmax_rho_ptr = C_LOC(lmax_rho)
if (present(lmax_pot)) lmax_pot_ptr = C_LOC(lmax_pot)
if (present(num_bands)) num_bands_ptr = C_LOC(num_bands)
if (present(num_mag_dims)) num_mag_dims_ptr = C_LOC(num_mag_dims)
if (present(pw_cutoff)) pw_cutoff_ptr = C_LOC(pw_cutoff)
if (present(gk_cutoff)) gk_cutoff_ptr = C_LOC(gk_cutoff)
if (present(auto_rmt)) auto_rmt_ptr = C_LOC(auto_rmt)
call sirius_set_parameters_aux(handler,lmax_apw_ptr,lmax_rho_ptr,lmax_pot_ptr,nu&
&m_bands_ptr,num_mag_dims_ptr,pw_cutoff_ptr,gk_cutoff_ptr,auto_rmt_ptr)
end subroutine sirius_set_parameters

!> @brief Set vectors of the unit cell.
!> @param [in] handler Simulation context handler
!> @param [in] a1 1st vector
!> @param [in] a2 2nd vector
!> @param [in] a3 3er vector
subroutine sirius_set_lattice_vectors_v2(handler,a1,a2,a3)
implicit none
type(C_PTR), intent(in) :: handler
real(C_DOUBLE), intent(in) :: a1
real(C_DOUBLE), intent(in) :: a2
real(C_DOUBLE), intent(in) :: a3
interface
subroutine sirius_set_lattice_vectors_v2_aux(handler,a1,a2,a3)&
&bind(C, name="sirius_set_lattice_vectors_v2")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: handler
real(C_DOUBLE), intent(in) :: a1
real(C_DOUBLE), intent(in) :: a2
real(C_DOUBLE), intent(in) :: a3
end subroutine
end interface
call sirius_set_lattice_vectors_v2_aux(handler,a1,a2,a3)
end subroutine sirius_set_lattice_vectors_v2

!> @brief Initialize simulation context.
!> @param [in] handler Simulation context handler.
subroutine sirius_initialize_context_v2(handler)
implicit none
type(C_PTR), intent(in) :: handler
interface
subroutine sirius_initialize_context_v2_aux(handler)&
&bind(C, name="sirius_initialize_context_v2")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: handler
end subroutine
end interface
call sirius_initialize_context_v2_aux(handler)
end subroutine sirius_initialize_context_v2

!> @brief Delete any object created by SIRIUS.
!> @param [inout] handler Handler of the object.
subroutine sirius_delete_object(handler)
implicit none
type(C_PTR), intent(inout) :: handler
interface
subroutine sirius_delete_object_aux(handler)&
&bind(C, name="sirius_delete_object")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(inout) :: handler
end subroutine
end interface
call sirius_delete_object_aux(handler)
end subroutine sirius_delete_object

!> @brief Set pointer to density or megnetization.
!> @param [in] handler Handler of the DFT ground state object.
!> @param [in] label Label of the function.
!> @param [in] f_mt Pointer to the muffin-tin part of the function.
!> @param [in] f_rg Pointer to the regualr-grid part of the function.
subroutine sirius_set_periodic_function_ptr(handler,label,f_mt,f_rg)
implicit none
type(C_PTR), intent(in) :: handler
character(C_CHAR), dimension(*), intent(in) :: label
real(C_DOUBLE), intent(in) :: f_mt
real(C_DOUBLE), intent(in) :: f_rg
interface
subroutine sirius_set_periodic_function_ptr_aux(handler,label,f_mt,f_rg)&
&bind(C, name="sirius_set_periodic_function_ptr")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: handler
character(C_CHAR), dimension(*), intent(in) :: label
real(C_DOUBLE), intent(in) :: f_mt
real(C_DOUBLE), intent(in) :: f_rg
end subroutine
end interface
call sirius_set_periodic_function_ptr_aux(handler,label,f_mt,f_rg)
end subroutine sirius_set_periodic_function_ptr

!> @brief Create k-point set from the list of k-points.
!> @param [in] handler Simulation context handler.
!> @param [out] ks_handler Handler of the created k-point set.
!> @param [in] num_kpoints Total number of k-points in the set.
!> @param [in] kpoints List of k-points in lattice coordinates.
!> @param [in] kpoint_weights Weights of k-points.
!> @param [in] init_kset If .true. k-set will be initialized.
subroutine sirius_create_kset_v2(handler,ks_handler,num_kpoints,kpoints,kpoint_w&
&eights,init_kset)
implicit none
type(C_PTR), intent(in) :: handler
type(C_PTR), intent(out) :: ks_handler
integer(C_INT), intent(in) :: num_kpoints
real(C_DOUBLE), intent(in) :: kpoints
real(C_DOUBLE), intent(in) :: kpoint_weights
logical(C_BOOL), intent(in) :: init_kset
interface
subroutine sirius_create_kset_v2_aux(handler,ks_handler,num_kpoints,kpoints,kpoi&
&nt_weights,init_kset)&
&bind(C, name="sirius_create_kset_v2")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: handler
type(C_PTR), intent(out) :: ks_handler
integer(C_INT), intent(in) :: num_kpoints
real(C_DOUBLE), intent(in) :: kpoints
real(C_DOUBLE), intent(in) :: kpoint_weights
logical(C_BOOL), intent(in) :: init_kset
end subroutine
end interface
call sirius_create_kset_v2_aux(handler,ks_handler,num_kpoints,kpoints,kpoint_wei&
&ghts,init_kset)
end subroutine sirius_create_kset_v2

!> @brief Create k-point set from the list of k-points.
!> @param [in] ks_handler Handler of the created k-point set.
!> @param [out] gs_handler Handler of the ground state object.
subroutine sirius_create_ground_state_v2(ks_handler,gs_handler)
implicit none
type(C_PTR), intent(in) :: ks_handler
type(C_PTR), intent(out) :: gs_handler
interface
subroutine sirius_create_ground_state_v2_aux(ks_handler,gs_handler)&
&bind(C, name="sirius_create_ground_state_v2")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: ks_handler
type(C_PTR), intent(out) :: gs_handler
end subroutine
end interface
call sirius_create_ground_state_v2_aux(ks_handler,gs_handler)
end subroutine sirius_create_ground_state_v2

