name: Build

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

jobs:

  build_and_test_cpu:
    runs-on: ubuntu-latest
    container: electronicstructure/sirius:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build SIRIUS
        run: |
          spack -e /sirius-env develop -p ${GITHUB_WORKSPACE} sirius@develop
          spack -e /sirius-env concretize -f
          spack -e /sirius-env install
      - name: Run unit tests
        run: |
          cd $(spack -e /sirius-env location -b sirius)
          spack -e /sirius-env --color always build-env sirius -- ctest --output-on-failure --label-exclude integration_test
      # - name: Run verification tests
      #   run: |
      #     cd $(spack -e /sirius-env location -b sirius)
      #     spack -e /sirius-env --color always build-env sirius -- ctest --output-on-failure -L cpu_serial
      # - name: Build QE
      #   run: |
      #     spack env create -d /q-e-sirius
      #     spack -e /q-e-sirius add q-e-sirius@=develop-ristretto
      #     # make sure to resuse previously installed sirius
      #     spack -e /q-e-sirius config add "packages:sirius:require:[$(spack -e /sirius-env find --format=\"/{hash}\" sirius)]"
      #     spack -e /q-e-sirius install
      - name: Build QE
        run: |
          cd ${GITHUB_WORKSPACE}
          git clone --depth 1 https://github.com/electronic-structure/q-e-sirius.git
          cd q-e-sirius
          mkdir build
          cd build
          spack -e /sirius-env --color always build-env sirius -- sh -c 'echo $CMAKE_PREFIX_PATH'
          find . $(spack -e /sirius-env find --format="{path}" sirius)
          spack -e /sirius-env --color always build-env sirius -- cmake .. -DQE_ENABLE_SIRIUS=1
          spack -e /sirius-env --color always build-env sirius -- make
