name: Build

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

jobs:

  build_and_test_cpu:
    runs-on: ubuntu-latest
    container: electronicstructure/sirius:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build SIRIUS
        run: |
          spack -e /sirius-env develop -p ${GITHUB_WORKSPACE} sirius@develop
          spack -e /sirius-env concretize -f
          spack -e /sirius-env install
      - name: Run unit tests
        run: |
          cd $(spack -e /sirius-env location -b sirius)
          spack -e /sirius-env --color always build-env sirius -- ctest --output-on-failure --label-exclude integration_test
      - name: Run verification tests
        run: |
          cd $(spack -e /sirius-env location -b sirius)
          spack -e /sirius-env --color always build-env sirius -- ctest --output-on-failure -L cpu_serial
      - name: Build QE
        run: |
          cd ${GITHUB_WORKSPACE}
          git clone --depth 1 https://github.com/electronic-structure/q-e-sirius.git
          cd q-e-sirius
          mkdir build
          cd build
          eval $(spack -e /sirius-env load --sh cmake)
          eval $(spack -e /sirius-env load --sh sirius)
          cmake .. -DQE_ENABLE_SIRIUS=1
          make
  build_and_test_clang:
    runs-on: ubuntu-latest
    container: electronicstructure/sirius:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build SIRIUS
        run: |
          spack -e /sirius-env-clang develop -p ${GITHUB_WORKSPACE} sirius@develop~openmp
          spack -e /sirius-env-clang concretize -f
          spack -e /sirius-env-clang install
