name: Check formatting of modified files

on:
  push:
    branches: ['master', 'develop', '!trying', '!staging']
  pull_request:
    branches: ['master', 'develop']

jobs:
  check:
    runs-on: ubuntu-latest
    container: zhongruoyu/llvm-ports:17.0.4-slim-focal
    steps:
      - uses: actions/checkout@v4
      - name: Check .cpp and .hpp files
        run: |
          find ./src -name \*.cpp -o -name \*.hpp ! -name nlohmann_json.hpp ! -name lebedev_grids.hpp | python3 check_format.py
          find ./apps -name \*.cpp -o -name \*.hpp | python3 check_format.py
          find ./python_module -maxdepth 1 -name \*.cpp -o -name \*.hpp | python3 check_format.py


