name: Check formatting of modified files

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 2
      - name: Check .cpp, .h and .hpp files
        run: |
            git log -2
            ./check_format.x
