name: Check generation of API

on:
  push:
    branches: ['master', 'develop']
  pull_request:
    branches: ['master', 'develop']

jobs:
  check:
    runs-on: ubuntu-latest
    container: zhongruoyu/llvm-ports:18.1.8-slim-bullseye
    steps:
      - uses: actions/checkout@v4
      - name: Check API generation
        run: |
          cd ./src/api
          apt update
          apt install -y python3-pip
          python3 -m pip install PyYAML
          python3 generate_api.py sirius_api.cpp


